version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    env_file:
      - '.env'
    ports:
    - "5432:5432"

  redis:
    image: 'redis:6'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    command: bundle exec sidekiq -d
    depends_on:
      - 'db'
      - 'redis'
    build: .
    volumes:
      - '.:/AlertWalutowy'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/AlertWalutowy
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  postgres:
  bundler_gems:
  redis:
